In [1]:
import numpy as np

In [9]:
motifs = [
    "TCGGGGgTTTtt", 
"cCGGtGAcTTaC", 
"aCGGGGATTTtC", 
"TtGGGGAcTTtt", 
"aaGGGGAcTTCC", 
"TtGGGGAcTTCC", 
"TCGGGGATTcat", 
"TCGGGGATTcCt", 
"TaGGGGAacTaC", 
"TCGGGtATaaCC"
]

In [10]:
motifs = [motif.upper() for motif in motifs]

In [11]:
motifs

['TCGGGGGTTTTT',
 'CCGGTGACTTAC',
 'ACGGGGATTTTC',
 'TTGGGGACTTTT',
 'AAGGGGACTTCC',
 'TTGGGGACTTCC',
 'TCGGGGATTCAT',
 'TCGGGGATTCCT',
 'TAGGGGAACTAC',
 'TCGGGTATAACC']

In [12]:
motifs_arr = np.array([list(motif) for motif in motifs])

In [13]:
motifs_arr

array([['T', 'C', 'G', 'G', 'G', 'G', 'G', 'T', 'T', 'T', 'T', 'T'],
       ['C', 'C', 'G', 'G', 'T', 'G', 'A', 'C', 'T', 'T', 'A', 'C'],
       ['A', 'C', 'G', 'G', 'G', 'G', 'A', 'T', 'T', 'T', 'T', 'C'],
       ['T', 'T', 'G', 'G', 'G', 'G', 'A', 'C', 'T', 'T', 'T', 'T'],
       ['A', 'A', 'G', 'G', 'G', 'G', 'A', 'C', 'T', 'T', 'C', 'C'],
       ['T', 'T', 'G', 'G', 'G', 'G', 'A', 'C', 'T', 'T', 'C', 'C'],
       ['T', 'C', 'G', 'G', 'G', 'G', 'A', 'T', 'T', 'C', 'A', 'T'],
       ['T', 'C', 'G', 'G', 'G', 'G', 'A', 'T', 'T', 'C', 'C', 'T'],
       ['T', 'A', 'G', 'G', 'G', 'G', 'A', 'A', 'C', 'T', 'A', 'C'],
       ['T', 'C', 'G', 'G', 'G', 'T', 'A', 'T', 'A', 'A', 'C', 'C']],
      dtype='<U1')

In [15]:
from scipy import stats

In [18]:
modes, counts = stats.mode(motifs_arr)

In [19]:
counts

array([[ 7,  6, 10, 10,  9,  9,  9,  5,  8,  7,  4,  6]])

In [20]:
modes

array([['T', 'C', 'G', 'G', 'G', 'G', 'A', 'T', 'T', 'T', 'C', 'C']],
      dtype='<U1')

In [21]:
scores = 10 - counts

In [23]:
scores.sum()

30

In [24]:
def get_scores(motifs):
    #motifs_arr = np.array([list(motif) for motif in motifs])
    modes, counts = stats.mode(motifs)
    scores = 10 - counts
    
    return scores.sum()

In [26]:
get_scores(motifs)

30

### Generate profiles

In [54]:
import pandas as pd

In [55]:
b = np.array([[1,2,3], [1,3,3], [2,2,3], [3,2,1]])
np.apply_along_axis(sorted, 0, b)

array([[1, 2, 1],
       [1, 2, 3],
       [2, 2, 3],
       [3, 3, 3]])

In [56]:
from collections import Counter

In [57]:
np.apply_along_axis(Counter, 0, b)

array([Counter({1: 2, 2: 1, 3: 1}), Counter({2: 3, 3: 1}),
       Counter({3: 3, 1: 1})], dtype=object)

In [61]:
see = np.apply_along_axis(Counter, 0, b)
see

array([Counter({1: 2, 2: 1, 3: 1}), Counter({2: 3, 3: 1}),
       Counter({3: 3, 1: 1})], dtype=object)

In [62]:
asd = [dict(c) for c in see]

In [63]:
pd.DataFrame(asd)

1    2  3
0  2.0  1.0  1
1  NaN  3.0  1
2  1.0  NaN  3

In [35]:
pd.DataFrame(np.apply_along_axis(dict(Counter), 0, b))

TypeError: descriptor 'keys' of 'dict' object needs an argument

In [103]:
motifs_arr

array([['T', 'C', 'G', 'G', 'G', 'G', 'G', 'T', 'T', 'T', 'T', 'T'],
       ['C', 'C', 'G', 'G', 'T', 'G', 'A', 'C', 'T', 'T', 'A', 'C'],
       ['A', 'C', 'G', 'G', 'G', 'G', 'A', 'T', 'T', 'T', 'T', 'C'],
       ['T', 'T', 'G', 'G', 'G', 'G', 'A', 'C', 'T', 'T', 'T', 'T'],
       ['A', 'A', 'G', 'G', 'G', 'G', 'A', 'C', 'T', 'T', 'C', 'C'],
       ['T', 'T', 'G', 'G', 'G', 'G', 'A', 'C', 'T', 'T', 'C', 'C'],
       ['T', 'C', 'G', 'G', 'G', 'G', 'A', 'T', 'T', 'C', 'A', 'T'],
       ['T', 'C', 'G', 'G', 'G', 'G', 'A', 'T', 'T', 'C', 'C', 'T'],
       ['T', 'A', 'G', 'G', 'G', 'G', 'A', 'A', 'C', 'T', 'A', 'C'],
       ['T', 'C', 'G', 'G', 'G', 'T', 'A', 'T', 'A', 'A', 'C', 'C']],
      dtype='<U1')

In [107]:
counter = np.apply_along_axis(Counter, 0, motifs_arr)
counter

array([Counter({'T': 7, 'A': 2, 'C': 1}),
       Counter({'C': 6, 'T': 2, 'A': 2}), Counter({'G': 10}),
       Counter({'G': 10}), Counter({'G': 9, 'T': 1}),
       Counter({'G': 9, 'T': 1}), Counter({'A': 9, 'G': 1}),
       Counter({'T': 5, 'C': 4, 'A': 1}),
       Counter({'T': 8, 'C': 1, 'A': 1}),
       Counter({'T': 7, 'C': 2, 'A': 1}),
       Counter({'C': 4, 'T': 3, 'A': 3}), Counter({'C': 6, 'T': 4})],
      dtype=object)

In [108]:
len(counter)

12

In [68]:
counter = [dict(c) for c in counter]

In [79]:
count_motifs = pd.DataFrame(counter)[list('ACGT')].fillna(0).T
count_motifs

0    1     2     3    4    5    6    7    8    9   10   11
A  2.0  2.0   0.0   0.0  0.0  0.0  9.0  1.0  1.0  1.0  3.0  0.0
C  1.0  6.0   0.0   0.0  0.0  0.0  0.0  4.0  1.0  2.0  4.0  6.0
G  0.0  0.0  10.0  10.0  9.0  9.0  1.0  0.0  0.0  0.0  0.0  0.0
T  7.0  2.0   0.0   0.0  1.0  1.0  0.0  5.0  8.0  7.0  3.0  4.0

In [80]:
count_motifs = count_motifs.to_numpy()
count_motifs

array([[ 2.,  2.,  0.,  0.,  0.,  0.,  9.,  1.,  1.,  1.,  3.,  0.],
       [ 1.,  6.,  0.,  0.,  0.,  0.,  0.,  4.,  1.,  2.,  4.,  6.],
       [ 0.,  0., 10., 10.,  9.,  9.,  1.,  0.,  0.,  0.,  0.,  0.],
       [ 7.,  2.,  0.,  0.,  1.,  1.,  0.,  5.,  8.,  7.,  3.,  4.]])

In [83]:
profile = count_motifs / len(motifs_arr)
profile

array([[0.2, 0.2, 0. , 0. , 0. , 0. , 0.9, 0.1, 0.1, 0.1, 0.3, 0. ],
       [0.1, 0.6, 0. , 0. , 0. , 0. , 0. , 0.4, 0.1, 0.2, 0.4, 0.6],
       [0. , 0. , 1. , 1. , 0.9, 0.9, 0.1, 0. , 0. , 0. , 0. , 0. ],
       [0.7, 0.2, 0. , 0. , 0.1, 0.1, 0. , 0.5, 0.8, 0.7, 0.3, 0.4]])

In [155]:
from collections import Counter
import pandas as pd

def get_profile(motifs):
    #motifs_arr = np.array([list(motif) for motif in motifs])
    
    counter = np.apply_along_axis(Counter, 0, motifs)
    counter = [dict(c) for c in counter]
    
    count_motifs = pd.DataFrame(counter, columns=list('ACGT')).fillna(0).T.to_numpy()
    
    profile = count_motifs / len(motifs)
    
    return profile

In [156]:
motifs

['TCGGGGGTTTTT',
 'CCGGTGACTTAC',
 'ACGGGGATTTTC',
 'TTGGGGACTTTT',
 'AAGGGGACTTCC',
 'TTGGGGACTTCC',
 'TCGGGGATTCAT',
 'TCGGGGATTCCT',
 'TAGGGGAACTAC',
 'TCGGGTATAACC']

In [157]:
motifs_arr

array([['T', 'C', 'G', 'G', 'G', 'G', 'G', 'T', 'T', 'T', 'T', 'T'],
       ['C', 'C', 'G', 'G', 'T', 'G', 'A', 'C', 'T', 'T', 'A', 'C'],
       ['A', 'C', 'G', 'G', 'G', 'G', 'A', 'T', 'T', 'T', 'T', 'C'],
       ['T', 'T', 'G', 'G', 'G', 'G', 'A', 'C', 'T', 'T', 'T', 'T'],
       ['A', 'A', 'G', 'G', 'G', 'G', 'A', 'C', 'T', 'T', 'C', 'C'],
       ['T', 'T', 'G', 'G', 'G', 'G', 'A', 'C', 'T', 'T', 'C', 'C'],
       ['T', 'C', 'G', 'G', 'G', 'G', 'A', 'T', 'T', 'C', 'A', 'T'],
       ['T', 'C', 'G', 'G', 'G', 'G', 'A', 'T', 'T', 'C', 'C', 'T'],
       ['T', 'A', 'G', 'G', 'G', 'G', 'A', 'A', 'C', 'T', 'A', 'C'],
       ['T', 'C', 'G', 'G', 'G', 'T', 'A', 'T', 'A', 'A', 'C', 'C']],
      dtype='<U1')

In [158]:
get_profile(motifs_arr)

array([[0.2, 0.2, 0. , 0. , 0. , 0. , 0.9, 0.1, 0.1, 0.1, 0.3, 0. ],
       [0.1, 0.6, 0. , 0. , 0. , 0. , 0. , 0.4, 0.1, 0.2, 0.4, 0.6],
       [0. , 0. , 1. , 1. , 0.9, 0.9, 0.1, 0. , 0. , 0. , 0. , 0. ],
       [0.7, 0.2, 0. , 0. , 0.1, 0.1, 0. , 0.5, 0.8, 0.7, 0.3, 0.4]])

## Generate profiles from one

In [159]:
motifs_curr = ['TCGGGGGTTTTT']

In [160]:
get_profile(motifs_new[0])

TypeError: iteration over a 0-d array

In [161]:
motifs_curr_arr = np.array([list(motif) for motif in motifs_curr])

In [162]:
motifs_curr_arr

array([['T', 'C', 'G', 'G', 'G', 'G', 'G', 'T', 'T', 'T', 'T', 'T']],
      dtype='<U1')

In [163]:
motifs_new[0][np.newaxis]

array([['T', 'C', 'G', 'G', 'G', 'G', 'G', 'T', 'T', 'T', 'T', 'T']],
      dtype='<U1')

In [164]:
get_profile(motifs_curr_arr)

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 1., 1., 1., 1., 1.]])

In [165]:
get_profile(motifs_new[0][np.newaxis])

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 1., 1., 1., 1., 1.]])

In [109]:
counter = np.apply_along_axis(Counter, 0, motifs_curr_arr)
counter

array([Counter({'T': 1}), Counter({'C': 1}), Counter({'G': 1}),
       Counter({'G': 1}), Counter({'G': 1}), Counter({'G': 1}),
       Counter({'G': 1}), Counter({'T': 1}), Counter({'T': 1}),
       Counter({'T': 1}), Counter({'T': 1}), Counter({'T': 1})],
      dtype=object)

In [110]:
len(counter)

12

In [114]:
counter = [dict(c) for c in counter]

In [117]:
pd.DataFrame(counter)

T    C    G
0   1.0  NaN  NaN
1   NaN  1.0  NaN
2   NaN  NaN  1.0
3   NaN  NaN  1.0
4   NaN  NaN  1.0
5   NaN  NaN  1.0
6   NaN  NaN  1.0
7   1.0  NaN  NaN
8   1.0  NaN  NaN
9   1.0  NaN  NaN
10  1.0  NaN  NaN
11  1.0  NaN  NaN

In [118]:
count_motifs = pd.DataFrame(counter, columns=list('ACGT')).fillna(0).T
count_motifs

0    1    2    3    4    5    6    7    8    9   10   11
A  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
C  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
G  0.0  0.0  1.0  1.0  1.0  1.0  1.0  0.0  0.0  0.0  0.0  0.0
T  1.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  1.0  1.0  1.0  1.0

In [124]:
motifs_curr_arr

array([['T', 'C', 'G', 'G', 'G', 'G', 'G', 'T', 'T', 'T', 'T', 'T']],
      dtype='<U1')

In [128]:
motifs_new = np.row_stack([motifs_curr_arr, motifs_curr_arr])

In [129]:
motifs_new

array([['T', 'C', 'G', 'G', 'G', 'G', 'G', 'T', 'T', 'T', 'T', 'T'],
       ['T', 'C', 'G', 'G', 'G', 'G', 'G', 'T', 'T', 'T', 'T', 'T']],
      dtype='<U1')

In [177]:
motifs_curr_arr[0, 0] = 'A'

In [178]:
motifs_curr_arr

array([['A', 'C', 'G', 'G', 'G', 'G', 'G', 'T', 'T', 'T', 'T', 'T']],
      dtype='<U1')

In [179]:
motifs_new = np.row_stack([motifs_new, motifs_curr_arr, motifs_curr_arr])

In [180]:
motifs_new

array([['T', 'C', 'G', 'G', 'G', 'G', 'G', 'T', 'T', 'T', 'T', 'T'],
       ['T', 'C', 'G', 'G', 'G', 'G', 'G', 'T', 'T', 'T', 'T', 'T'],
       ['T', 'C', 'G', 'G', 'G', 'G', 'G', 'T', 'T', 'T', 'T', 'T'],
       ['T', 'C', 'G', 'G', 'G', 'G', 'G', 'T', 'T', 'T', 'T', 'T'],
       ['T', 'C', 'G', 'G', 'G', 'G', 'G', 'T', 'T', 'T', 'T', 'T'],
       ['T', 'C', 'G', 'G', 'G', 'G', 'G', 'T', 'T', 'T', 'T', 'T'],
       ['A', 'C', 'G', 'G', 'G', 'G', 'G', 'T', 'T', 'T', 'T', 'T'],
       ['A', 'C', 'G', 'G', 'G', 'G', 'G', 'T', 'T', 'T', 'T', 'T']],
      dtype='<U1')

In [133]:
motifs_new[0].shape

(12,)

In [142]:
motifs_new[0]

array(['T', 'C', 'G', 'G', 'G', 'G', 'G', 'T', 'T', 'T', 'T', 'T'],
      dtype='<U1')

In [150]:
get_profile(motifs_new[0])

array([[0.16666667, 0.16666667, 0.        , 0.        , 0.        ,
        0.        , 0.75      , 0.08333333, 0.08333333, 0.08333333,
        0.25      , 0.        ],
       [0.08333333, 0.5       , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.33333333, 0.08333333, 0.16666667,
        0.33333333, 0.5       ],
       [0.        , 0.        , 0.83333333, 0.83333333, 0.75      ,
        0.75      , 0.08333333, 0.        , 0.        , 0.        ,
        0.        , 0.        ],
       [0.58333333, 0.16666667, 0.        , 0.        , 0.08333333,
        0.08333333, 0.        , 0.41666667, 0.66666667, 0.58333333,
        0.25      , 0.33333333]])

In [151]:
get_profile(motifs_arr)

array([[0.2, 0.2, 0. , 0. , 0. , 0. , 0.9, 0.1, 0.1, 0.1, 0.3, 0. ],
       [0.1, 0.6, 0. , 0. , 0. , 0. , 0. , 0.4, 0.1, 0.2, 0.4, 0.6],
       [0. , 0. , 1. , 1. , 0.9, 0.9, 0.1, 0. , 0. , 0. , 0. , 0. ],
       [0.7, 0.2, 0. , 0. , 0.1, 0.1, 0. , 0.5, 0.8, 0.7, 0.3, 0.4]])

In [170]:
def get_scores(motifs):
    #motifs_arr = np.array([list(motif) for motif in motifs])
    modes, counts = stats.mode(motifs)
    scores = 10 - counts
    
    return scores.sum()

In [172]:
motifs_arr

array([['T', 'C', 'G', 'G', 'G', 'G', 'G', 'T', 'T', 'T', 'T', 'T'],
       ['C', 'C', 'G', 'G', 'T', 'G', 'A', 'C', 'T', 'T', 'A', 'C'],
       ['A', 'C', 'G', 'G', 'G', 'G', 'A', 'T', 'T', 'T', 'T', 'C'],
       ['T', 'T', 'G', 'G', 'G', 'G', 'A', 'C', 'T', 'T', 'T', 'T'],
       ['A', 'A', 'G', 'G', 'G', 'G', 'A', 'C', 'T', 'T', 'C', 'C'],
       ['T', 'T', 'G', 'G', 'G', 'G', 'A', 'C', 'T', 'T', 'C', 'C'],
       ['T', 'C', 'G', 'G', 'G', 'G', 'A', 'T', 'T', 'C', 'A', 'T'],
       ['T', 'C', 'G', 'G', 'G', 'G', 'A', 'T', 'T', 'C', 'C', 'T'],
       ['T', 'A', 'G', 'G', 'G', 'G', 'A', 'A', 'C', 'T', 'A', 'C'],
       ['T', 'C', 'G', 'G', 'G', 'T', 'A', 'T', 'A', 'A', 'C', 'C']],
      dtype='<U1')

In [173]:
get_scores(motifs_arr)

30